In [3]:
!pip install numpy

In [5]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])

In [9]:
arr

array([1, 2, 3, 4, 5])

In [11]:
x1 = arr.view()

In [13]:
x1

array([1, 2, 3, 4, 5])

In [15]:
x1 = arr.copy()

In [17]:
x1

array([1, 2, 3, 4, 5])

In [19]:
arr1 = np.array([6,7,8,9,10])

In [21]:
arr1

array([ 6,  7,  8,  9, 10])

In [25]:
newarr = np.concatenate((arr,arr1))

In [27]:
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
newarr1 = np.dstack((arr,arr1))

In [41]:
newarr1

array([[[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]]])

In [43]:
newarr1 = np.vstack((arr,arr1))

In [45]:
newarr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
newarr1 = np.where((newarr==3))

In [55]:
newarr1

(array([2]),)

In [5]:
import random

In [39]:
x = random.randint(1,100)

In [41]:
x

67

In [45]:
import numpy as np

In [49]:
x = np.random.randint(1,100,size=5)

In [51]:
x

array([14, 25, 40, 77, 61])

In [57]:
x = np.random.randint(2,100,size=(3,5))

In [59]:
x

array([[ 6, 59, 62, 50, 75],
       [91,  7, 44, 44, 71],
       [38,  6, 16, 83, 34]])

In [69]:
uinput = input("Enter numbers separated by spaces: ")
arr = np.array(list(map(int, uinput.split())))
print('Array = ',arr)

Enter numbers separated by spaces:  5 6 7 8 9 10 11


Array =  [ 5  6  7  8  9 10 11]
